grails-app/domain/tp1/SaleAd.groovy
package tp1

class SaleAd {

    String title
    String description
    String longDescription

    Date dateCreated
    Date lastUpdated

    Float price

    List illustrations

    static hasMany = [illustrations: Illustration]

    static belongsTo = [author:User]


    static constraints = {
        title blank: false, nullable: false
        description blank: false, nullable:false
        longDescription blank: false, nullable: false
        illustrations nullable:true
        price min: 0F
    }
    static mapping = {
        longDescription type: 'text'
    }
    @Override
    String toString(){
        return title
    }
}

grails-app/controllers/tp1/SaleAdController.groovy
package tp1
import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException
import org.apache.commons.lang.RandomStringUtils

import static org.springframework.http.HttpStatus.*


//@Secured(['ROLE_ADMIN', 'ROLE_MODERATOR'])
class SaleAdController {
    SaleAdService saleAdService
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond saleAdService.list(params), model:[saleAdCount: saleAdService.count()]
    }
    def show(Long id) {
        respond saleAdService.get(id)
    }
    def create() {
        respond new SaleAd(params)
    }

    def save(SaleAd saleAd) {
        if (saleAd == null) {
            notFound()
            return
        }

        try {
            def user = User.get(params.author)

            request.multipartFiles.eachWithIndex {
                def mfile, int index ->
                    def f = request.getFile(mfile.key)
                    String charset = (('A'..'Z') + ('0'..'9')).join()
                    Integer length = 9
                    String randomString = RandomStringUtils.random(length, charset.toCharArray())
                    File file = new File(grailsApplication.config.tp1.illustrations.path + randomString +'.png')
                    f.transferTo(file)
                    saleAd.addToIllustrations(new Illustration(filename: file.getName()))
            }

            saleAdService.save(saleAd)
            user.addToSaleAds(saleAd)
            user.save(flush: true, failOnError: true)
        } catch (ValidationException e) {
            respond saleAd.errors, view:'create'
            return
        }
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'saleAd.label', default: 'SaleAd'), saleAd.id])
                redirect saleAd
            }
            '*' { respond saleAd, [status: CREATED] }
        }
    }
    def edit(Long id) {
        respond saleAdService.get(id)
    }
    def update(SaleAd saleAd) {
        if (saleAd == null) {
            notFound()
            return
        }
        try {
            saleAdService.save(saleAd)
        } catch (ValidationException e) {
            respond saleAd.errors, view:'edit'
            return
        }
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'saleAd.label', default: 'SaleAd'), saleAd.id])
                redirect saleAd
            }
            '*'{ respond saleAd, [status: OK] }
        }
    }
    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }
        saleAdService.delete(id)
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'saleAd.label', default: 'SaleAd'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }
    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'saleAd.label', default: 'SaleAd'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/saleAd/create.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main" />
    <g:set var="entityName" value="${message(code: 'saleAd.label', default: 'SaleAd')}" />
    <title><g:message code="default.create.label" args="[entityName]" /></title>
</head>
<body>
<a href="#create-saleAd" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
    </ul>
</div>
<div id="create-saleAd" class="content scaffold-create" role="main">
    <h1><g:message code="default.create.label" args="[entityName]" /></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${this.saleAd}">
        <ul class="errors" role="alert">
            <g:eachError bean="${this.saleAd}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:uploadForm controller="saleAd" action="save" method="POST">

        <div class='fieldcontain required'>

            <label for='title'>Title
                <span class='required-indicator'>*</span>
            </label><input type="text" name="title" value="" required="" id="title"/><br><br>

            <label for='title'>Description
                <span class='required-indicator'>*</span>
            </label><input type="descShort" name="description" value="" required="" id="descShort"/><br><br>

            <label for='title'>Long Description
                <span class='required-indicator'>*</span>
            </label><input type="descLong" name="longDescription" value="" required="" id="descLong"/><br><br>

            <label for='title'>price
                <span class='required-indicator'>*</span>
            </label><input type="price" name="price" value="" required="" id="price"/><br><br>
            <div class="form-group">
                <label for="filename0">Illustration(s)</label>

                <input class="form-control" type="file" name="filename0" id="filename0">

                <br>

                <div class="content" id="wrapper"></div>

                <input class="form-control" type="button" id="more_fields" onclick="add_fields()"
                        value="Ajouter une illustration">
            </div>
            <div class="form-group required">
                <label for="author">Author
                    <span class="required-indicator">*</span>
                </label>
                <g:select class="form-control" name="author" from="${tp1.User.list()}"
                      optionKey="id"
                      optionValue="username"/>
            </div>


        <fieldset class="buttons">
            <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
        </fieldset>
    </g:uploadForm>
</div>


    <script>
        var i = 1;

        function add_fields() {
            i++;
            document.getElementById('wrapper').innerHTML += '<input class="form-control" type="file" name="filename' + i + '" id="filename' + i + '"><br>\r\n';
        }
    </script>

</body>
</html>

grails-app/views/saleAd/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'saleAd.label', default: 'SaleAd')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-saleAd" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-saleAd" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.saleAd}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.saleAd}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.saleAd}" method="PUT">
                <g:hiddenField name="version" value="${this.saleAd?.version}" />
                <fieldset class="form">
                    <f:all bean="saleAd"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/saleAd/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'saleAd.label', default: 'SaleAd')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>

    </head>
    <body>
    <style>
    body
    {
        background-color: #2f4f4f;
    }
    </style>
        <a href="#list-saleAd" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-saleAd" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <table>
                <thead>
                <tr>
                    <th class="sortable" ><a href="/tp1/saleAd/index?sort=title&amp;max=10&amp;order=asc">Title</a></th>
                    <th class="sortable" ><a href="/tp1/saleAd/index?sort=description&amp;max=10&amp;order=asc">Description</a></th>
                    <th class="sortable" ><a href="/tp1/saleAd/index?sort=longDescription&amp;max=10&amp;order=asc">Long Description</a></th>
                    <th class="sortable" ><a href="/tp1/saleAd/index?sort=illustrations&amp;max=10&amp;order=asc">Illustrations</a></th>
                    <th class="sortable" ><a href="/tp1/saleAd/index?sort=price&amp;max=10&amp;order=asc">Price</a></th>
                    <th class="sortable" ><a href="/tp1/saleAd/index?sort=author&amp;max=10&amp;order=asc">Author</a></th>
                </tr>
                </thead>
                <tbody>
                <g:each in="${saleAdList}" var="saleAd">
                    <tr class="even">


                        <td><a href="${grailsApplication.config.tp1.illustrations.grailsurl + "saleAd/show/" + saleAd.id}">${saleAd.title}</a></td>
                        <td>${saleAd.description}</td>
                        <td>${saleAd.longDescription}</td>
                        <td><ul><li>
                            <g:each in="${saleAd.illustrations}" var="illustration" status="i">
                                <g:if test="${i <= 3}">
                                    <img src="${grailsApplication.config.tp1.illustrations.url + illustration.filename}">
                                </g:if>
                            </g:each>
                        </li></ul></td>
                        <td>${saleAd.price}</td>
                        <td>${saleAd.author.username}</td>
                    </tr>
                </g:each>
                </tbody>
            </table>

            <div class="pagination">

            </div>
        </div>


    </body>
</html>

grails-app/views/saleAd/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'saleAd.label', default: 'SaleAd')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-saleAd" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-saleAd" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>







            <ol class="property-list saleAd">
                <li class="fieldcontain">
                    <div class="property-value" aria-labelledby="illustrations-label">
                        <g:each in="${this.saleAd.illustrations}" var="illustration">
                                <img style="width: 200px;" src="${grailsApplication.config.tp1.illustrations.url}${illustration.filename}" class="d-block w-100" alt="...">
                        </g:each>
                    </div>
                </li>

                <li class="fieldcontain">
                    <span id="price-label" class="property-label">Price</span>

                    <div class="property-value" aria-labelledby="price-label">${this.saleAd.price}</div>
                </li>

                <li class="fieldcontain">
                    <span id="description-label" class="property-label">Description</span>

                    <div class="property-value" aria-labelledby="description-label">${this.saleAd.description}</div>
                </li>

                <li class="fieldcontain">
                    <span id="longDescription-label" class="property-label">Long Description</span>

                    <div class="property-value" aria-labelledby="longDescription-label">${this.saleAd.longDescription}</div>
                </li>

                <li class="fieldcontain">
                    <span id="author-label" class="property-label">Author</span>

                    <div class="property-value" aria-labelledby="author-label">
                        <g:link controller="user" action="show" id="${this.saleAd.id}">
                            ${this.saleAd.author}
                        </g:link>
                    </div>
                </li>
            </ol>






            <g:if test="${flash.message}">

            <div class="message" role="status">${flash.message}</div>
            </g:if>



%{--            <f:display bean="saleAd" />--}%



            <g:form resource="${this.saleAd}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.saleAd}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>